<?php

/**
 * Implements hook_init().
 *
 * Require the Composer Autoload File.
 */
function composer_autoloader_init() {

  // Define the default path to the  composer autoloader.
  $default = DRUPAL_ROOT . '/../vendor/autoload.php';

  // Allow the path to be modified by $conf.
  $autoloader = variable_get('composer_autoloader', $default);

  // Determine if the file exists.
  if (!file_exists($autoloader)) {

    // If the current path is an admin path, display an error.
    if (path_is_admin(current_path())) {

      // The error message text.
      $text = 'Autoloader not found: @file';

      // Variables for the text.
      $variables = array('@file' => $autoloader);

      // Set the message.
      drupal_set_message(t($text, $variables), 'error', FALSE);

    }

    // Error type is the name of the module.
    $type = 'composer_autoloader';

    // Add the error to the log.
    watchdog($type, $text, $variables, WATCHDOG_ALERT);

    // End the funciton.
    return;

  }

  // Require the Autoloader.
  require_once $autoloader;

}
